name: CICD

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-output
          path: dist/
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-output
      - name: Show current path
        run: pwd
      - name: List files
        run: ls
